---
apiVersion: v1
kind: Namespace
metadata:
  name: test-zipkin
---
apiVersion: v1
kind: Pod
metadata:
  name: zipkin
  namespace: test-zipkin
spec:
  containers:
  - name: zipkin
    image: openzipkin/zipkin:2.21.1
    ports:
    - containerPort: 9410
    env:
      - name: STORAGE_TYPE
        value: mem
      - name: QUERY_PORT
        value: "9410"
  - name: proxy
    image: registry.local:5000/proxy:latest
