---
apiVersion: v1
kind: Namespace
metadata:
  name: test-zipkin
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: zipkin
rules:
- apiGroups:
  - ""
  resources:
  - pods
  - namespaces
  verbs:
  - list
  - watch
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: zipkin
  namespace: test-zipkin
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: zipkin
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: zipkin
subjects:
- kind: ServiceAccount
  name: zipkin
  namespace: test-zipkin
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: zipkin
  namespace: test-zipkin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zipkin
  template:
    metadata:
      labels:
        app: zipkin
    spec:
      containers:
      - name: zipkin
        image: openzipkin/zipkin:2.21.1
        ports:
        - containerPort: 9410
        env:
          - name: STORAGE_TYPE
            value: mem
          - name: QUERY_PORT
            value: "9410"
      - name: proxy
        image: registry.local:5000/proxy:latest
      serviceAccount: zipkin
---
apiVersion: v1
kind: Service
metadata:
  name: zipkin
  namespace: test-zipkin
spec:
  type: ClusterIP
  selector:
    app: zipkin
  ports:
    - port: 9410
      targetPort: 9410
      protocol: TCP
      name: tcp-zipkin
    - port: 9411
      targetPort: 9411
      protocol: TCP
      name: tcp-proxy
