---
apiVersion: v1
kind: Namespace
metadata:
  name: test-zipkin
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: zipkin
rules:
- apiGroups:
  - ""
  resources:
  - pods
  - namespaces
  verbs:
  - list
  - watch
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: zipkin
  namespace: test-zipkin
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: zipkin
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: zipkin
subjects:
- kind: ServiceAccount
  name: zipkin
  namespace: test-zipkin
---
apiVersion: v1
kind: Pod
metadata:
  name: zipkin
  namespace: test-zipkin
spec:
  containers:
  - name: zipkin
    image: openzipkin/zipkin:2.21.1
    ports:
    - containerPort: 9410
    env:
      - name: STORAGE_TYPE
        value: mem
      - name: QUERY_PORT
        value: "9410"
  - name: proxy
    image: registry.local:5000/proxy:latest
  serviceAccount: zipkin
